name: iOS CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install kivy-ios
      run: |
        pip install kivy-ios
        
    - name: Build Kivy for iOS
      run: |
        toolchain build kivy
        
    - name: Create Xcode project
      run: |
        toolchain create EZNarratives
        
    - name: Set up code signing
      uses: apple-actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.IOS_P12_CERTIFICATE }}
        p12-password: ${{ secrets.IOS_P12_PASSWORD }}
        keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
        
    - name: Build and archive iOS app
      run: |
        cd EZNarratives-ios
        xcodebuild -workspace EZNarratives.xcworkspace -scheme EZNarratives -configuration Release -archivePath EZNarratives.xcarchive archive
        
    - name: Export IPA
      run: |
        cd EZNarratives-ios
        xcodebuild -exportArchive -archivePath EZNarratives.xcarchive -exportOptionsPlist exportOptions.plist -exportPath ./build
        
    - name: Upload to TestFlight
      uses: apple-actions/upload-testflight-build@v1
      with:
        app-path: EZNarratives-ios/build/EZNarratives.ipa
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}